from pathlib import Path

from cliolens import __version__
from cliolens.formatter import MarkdownFormatter, TreeRenderer, fence_for, language_for
from cliolens.scanner import FileEntry, ScanResult, SkipRecord

# --------------------------------------------------------------------- tree


def test_tree_dirs_before_files():
    tree = TreeRenderer().render(
        "proj",
        ["src", "src/utils"],
        ["README.md", "src/main.py", "src/utils/helpers.py"],
    )
    assert tree.splitlines() == [
        "proj/",
        "├── src/",
        "│   ├── utils/",
        "│   │   └── helpers.py",
        "│   └── main.py",
        "└── README.md",
    ]


def test_tree_alphabetical_within_groups():
    tree = TreeRenderer().render("p", ["beta", "alpha"], ["z.txt", "a.txt"])
    assert tree.splitlines() == [
        "p/",
        "├── alpha/",
        "├── beta/",
        "├── a.txt",
        "└── z.txt",
    ]


def test_tree_empty_project():
    assert TreeRenderer().render("p", [], []) == "p/"


# ----------------------------------------------------------------- language


def test_language_for_known_extensions():
    assert language_for("src/main.py") == "python"
    assert language_for("x.test.js") == "javascript"
    assert language_for("README.md") == "markdown"
    assert language_for("config.yaml") == "yaml"
    assert language_for("a/b/script.sh") == "bash"
    assert language_for("win.bat") == "batch"
    assert language_for("lib.hpp") == "cpp"


def test_language_for_unknown_or_missing():
    assert language_for("Makefile") == ""
    assert language_for(".gitignore") == ""
    assert language_for("archive.zzz") == ""


# ----------------------------------------------------------------- document


def _sample_result(root: Path) -> ScanResult:
    result = ScanResult(root=root)
    result.directories = ["src"]
    result.entries = [
        FileEntry(
            "src/main.py", root / "src" / "main.py", 30,
            content="def main():\n    print('hi')\n",
        ),
        FileEntry("README.md", root / "README.md", 7, content="# Demo\n"),
        FileEntry(
            "logo.png", root / "logo.png", 2048,
            is_binary=True, mime_type="image/png",
        ),
    ]
    result.files_scanned = 5
    result.skipped = [
        SkipRecord("junk.pyc", "excluded (built-in: *.pyc)"),
    ]
    result.total_bytes = 2085
    return result


def test_document_structure(tmp_path):
    doc = MarkdownFormatter(max_file_size_label="100KB").format(
        _sample_result(tmp_path / "demo")
    )
    assert doc.startswith("# Project Context Dump")
    assert doc.index("## Metadata") < doc.index("## Directory Tree") < doc.index("## File Contents")
    assert "**Project Name:** demo" in doc
    assert "**Files Scanned:** 5" in doc
    assert "**Files Included:** 3" in doc
    assert "**Files Skipped:** 1" in doc
    assert "### src/main.py" in doc
    assert "```python" in doc
    assert "### README.md" in doc
    assert "### logo.png" in doc       # binary placeholder always shown
    assert "[Binary file:" in doc
    assert f"End of dump. Generated by cliolens v{__version__}" in doc
    assert "@@" not in doc  # placeholders fully substituted


def test_truncation_notice(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "big.js", tmp_path / "big.js", 450 * 1024,
            content="\n".join(f"l{i}" for i in range(50)),
            truncated=True, omitted_lines=1200,
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "Content truncated: file is 450.0KB, max allowed is 100KB" in doc
    assert "First 50 lines shown below:" in doc
    assert "1,200 more lines omitted" in doc


def test_truncation_uses_language_comment_marker(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "big.py", tmp_path / "big.py", 200_000,
            content="x = 1", truncated=True, omitted_lines=10,
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "# [Content truncated" in doc  # '#' for python, not '//'


def test_binary_placeholder_by_default(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "assets/img.png", tmp_path / "img.png", 24_576,
            is_binary=True, mime_type="image/png",
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "### assets/img.png" in doc
    assert "[Binary file: image/png, 24.0KB — content omitted]" in doc


def test_binary_base64_rendered(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "assets/img.png", tmp_path / "img.png", 3,
            is_binary=True, mime_type="image/png",
            content="AQID",  # base64 of b"\x01\x02\x03"
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "AQID" in doc
    assert "content omitted" not in doc


def test_binary_truncated_base64_rendered(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "assets/big.png", tmp_path / "big.png", 102_400,
            is_binary=True, mime_type="image/png",
            content="AQID", truncated=True, omitted_bytes=101_376,
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "AQID" in doc
    assert "Binary content truncated" in doc
    assert "content omitted" not in doc


def test_fence_for():
    assert fence_for("plain") == "```"
    assert fence_for("has ``` inside") == "````"
    assert fence_for("`````` six") == "```````"


def test_fence_escalates_for_backtick_content(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "README.md", tmp_path / "README.md", 40,
            content="# Title\n\n```python\nprint('hi')\n```\n",
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "````markdown" in doc                    # outer fence escalated
    assert "```python\nprint('hi')\n```" in doc     # inner fence verbatim


def test_fence_stays_triple_for_plain_content(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [FileEntry("a.py", tmp_path / "a.py", 8, content="x = 1\n")]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "```python" in doc
    assert "````" not in doc


def test_source_containing_placeholder_text_is_preserved(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "tricky.py", tmp_path / "tricky.py", 28,
            content='PH = "@@CLIOLENS_TOKENS@@"\n',
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert '"@@CLIOLENS_TOKENS@@"' in doc           # verbatim, not corrupted
    assert "**Estimated Tokens:** 0" not in doc     # real numbers present
