from pathlib import Path

from cliolens import __version__
from cliolens.formatter import MarkdownFormatter, TreeRenderer, language_for
from cliolens.scanner import FileEntry, ScanResult, SkipRecord

# --------------------------------------------------------------------- tree


def test_tree_dirs_before_files():
    tree = TreeRenderer().render(
        "proj",
        ["src", "src/utils"],
        ["README.md", "src/main.py", "src/utils/helpers.py"],
    )
    assert tree.splitlines() == [
        "proj/",
        "├── src/",
        "│   ├── utils/",
        "│   │   └── helpers.py",
        "│   └── main.py",
        "└── README.md",
    ]


def test_tree_alphabetical_within_groups():
    tree = TreeRenderer().render("p", ["beta", "alpha"], ["z.txt", "a.txt"])
    assert tree.splitlines() == [
        "p/",
        "├── alpha/",
        "├── beta/",
        "├── a.txt",
        "└── z.txt",
    ]


def test_tree_empty_project():
    assert TreeRenderer().render("p", [], []) == "p/"


# ----------------------------------------------------------------- language


def test_language_for_known_extensions():
    assert language_for("src/main.py") == "python"
    assert language_for("x.test.js") == "javascript"
    assert language_for("README.md") == "markdown"
    assert language_for("config.yaml") == "yaml"
    assert language_for("a/b/script.sh") == "bash"
    assert language_for("win.bat") == "batch"
    assert language_for("lib.hpp") == "cpp"


def test_language_for_unknown_or_missing():
    assert language_for("Makefile") == ""
    assert language_for(".gitignore") == ""
    assert language_for("archive.zzz") == ""


# ----------------------------------------------------------------- document


def _sample_result(root: Path) -> ScanResult:
    result = ScanResult(root=root)
    result.directories = ["src"]
    result.entries = [
        FileEntry(
            "src/main.py", root / "src" / "main.py", 30,
            content="def main():\n    print('hi')\n",
        ),
        FileEntry("README.md", root / "README.md", 7, content="# Demo\n"),
    ]
    result.files_scanned = 5
    result.skipped = [
        SkipRecord("junk.pyc", "excluded (built-in: *.pyc)"),
        SkipRecord("logo.png", "binary"),
    ]
    result.total_bytes = 37
    return result


def test_document_structure(tmp_path):
    doc = MarkdownFormatter(max_file_size_label="100KB").format(
        _sample_result(tmp_path / "demo")
    )
    assert doc.startswith("# Project Context Dump")
    assert doc.index("## Metadata") < doc.index("## Directory Tree") < doc.index("## File Contents")
    assert "**Project Name:** demo" in doc
    assert "**Files Scanned:** 5" in doc
    assert "**Files Included:** 2" in doc
    assert "**Files Skipped:** 2" in doc
    assert "### src/main.py" in doc
    assert "```python" in doc
    assert "### README.md" in doc
    assert f"End of dump. Generated by cliolens v{__version__}" in doc
    assert "@@" not in doc  # placeholders fully substituted


def test_truncation_notice(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "big.js", tmp_path / "big.js", 450 * 1024,
            content="\n".join(f"l{i}" for i in range(50)),
            truncated=True, omitted_lines=1200,
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "Content truncated: file is 450.0KB, max allowed is 100KB" in doc
    assert "First 50 lines shown below:" in doc
    assert "1,200 more lines omitted" in doc


def test_truncation_uses_language_comment_marker(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "big.py", tmp_path / "big.py", 200_000,
            content="x = 1", truncated=True, omitted_lines=10,
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "# [Content truncated" in doc  # '#' for python, not '//'


def test_binary_notice(tmp_path):
    result = ScanResult(root=tmp_path / "demo")
    result.entries = [
        FileEntry(
            "assets/img.png", tmp_path / "img.png", 24_576,
            is_binary=True, mime_type="image/png",
        )
    ]
    doc = MarkdownFormatter(max_file_size_label="100KB").format(result)
    assert "[Binary file: image/png, 24.0KB — content omitted]" in doc
